// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_uJ7XxdSK55OdLKWWA2WLHGNb8kouS6Y',
    appId: '1:674494963473:web:5b64928dbbd1e556a576b0',
    messagingSenderId: '674494963473',
    projectId: 'zartecmachinetest',
    authDomain: 'zartecmachinetest.firebaseapp.com',
    storageBucket: 'zartecmachinetest.firebasestorage.app',
    measurementId: 'G-041J56DC8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tn18ATYw075MjLbZTWxPF6NU3Umy5gQ',
    appId: '1:674494963473:android:0c0db8b8039e8428a576b0',
    messagingSenderId: '674494963473',
    projectId: 'zartecmachinetest',
    storageBucket: 'zartecmachinetest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZX9waHNMUUXkMCqCUQi4WuvDQDgV830',
    appId: '1:674494963473:ios:7d5b6ab534a7154da576b0',
    messagingSenderId: '674494963473',
    projectId: 'zartecmachinetest',
    storageBucket: 'zartecmachinetest.firebasestorage.app',
    androidClientId: '674494963473-64djiphb4m4eidi3776v2abppuvkt8to.apps.googleusercontent.com',
    iosClientId: '674494963473-kvcquti4arsatus44a5f05g5jo1id2cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zartechmachinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZX9waHNMUUXkMCqCUQi4WuvDQDgV830',
    appId: '1:674494963473:ios:7d5b6ab534a7154da576b0',
    messagingSenderId: '674494963473',
    projectId: 'zartecmachinetest',
    storageBucket: 'zartecmachinetest.firebasestorage.app',
    androidClientId: '674494963473-64djiphb4m4eidi3776v2abppuvkt8to.apps.googleusercontent.com',
    iosClientId: '674494963473-kvcquti4arsatus44a5f05g5jo1id2cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zartechmachinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_uJ7XxdSK55OdLKWWA2WLHGNb8kouS6Y',
    appId: '1:674494963473:web:544064cbedc3e4b3a576b0',
    messagingSenderId: '674494963473',
    projectId: 'zartecmachinetest',
    authDomain: 'zartecmachinetest.firebaseapp.com',
    storageBucket: 'zartecmachinetest.firebasestorage.app',
    measurementId: 'G-EFQX5NW04D',
  );
}
